jcrist/skein

java/src/main/java/com/anaconda/skein/ApplicationMaster.java
java/src/main/proto/skein.proto
skein/cli.py
skein/core.py
skein/proto/__init__.py
skein/test/test_core.py

Allows for stopping an application master without explicitly killing it.

Add `shutdown` method to `ApplicationClient`

---

skein/cli.py
skein/test/test_cli.py

List all applications and containers instead of just the active ones.
- `skein application ls -a`
- `skein container ls -a`

Add `ls -a` support

---

docs/source/quickstart.rst
skein/cli.py
skein/core.py
skein/test/conftest.py
skein/test/test_cli.py
skein/test/test_core.py

No longer require running `skein init` before anything else. Now
defaults will be written (with a warning) on the first call
automatically.

Automatically initialize configuration

---

skein/model.py
skein/test/test_model.py

Previously we'd error if relative paths were used in code (not in a
specification file). While usually using absolute paths is more robust,
for interactive uses relative paths can be nice.

Support relative paths

---

docs/source/quickstart.rst
skein/cli.py
skein/core.py
skein/test/test_cli.py

- Rename `init` to `config gencerts`
- Don't require daemon running before cli commands (fixes #25).

Cli nicities

---

java/src/main/java/com/anaconda/skein/MsgUtils.java
java/src/main/proto/skein.proto
skein/model.py
skein/test/test_model.py

Closes #38
I thought about adding a `NodeId` message to the ProtoBuf, but a `str` is simpler and seems to be sufficient for now, wdyt?

Exposed YARN node address in the ProtoBuf and Python API

---

skein/model.py
skein/test/test_model.py

Previously on Python 2.X the instances were compared using reference
(as opposed to structural) equality. This can be easily verified by
running the following:
>>> class A:
...     def __init__(self, a):
...         self.a = a
...     def __eq__(self, other):
...         return self.a == other.a
...
>>> A(42) == A(42)
True
>>> A(42) != A(42)
True
Note that on Python 3.X the output is True/False as expected.

Implemented ``Base.__ne__``

---

docs/source/api.rst
java/pom.xml
java/src/main/java/com/anaconda/skein/ApplicationMaster.java
java/src/main/java/com/anaconda/skein/IntervalTree.java
java/src/main/java/com/anaconda/skein/Model.java
java/src/main/proto/skein.proto
java/src/test/java/com/anaconda/skein/TestIntervalTree.java
skein/__init__.py
skein/cli.py
skein/compatibility.py
skein/core.py
skein/exceptions.py
skein/kv.py
skein/model.py
skein/objects.py
skein/proto/__init__.py
skein/test/test_cli.py
skein/test/test_core.py
skein/test/test_kv.py
skein/test/test_model.py
skein/test/test_utils.py
skein/utils.py

This is a rewrite of the key-value store to enable more concurrency primitives. The core design is borrowed from etcd, with changes made to simplify things where possible.
Todo:
Fixes #33, Fixes #35.

Rewrite Key Value store

---

docs/source/api.rst
skein/__init__.py
skein/compatibility.py
skein/core.py
skein/exceptions.py
skein/test/conftest.py
skein/test/test_core.py

Add `properties` object, which stores immutable runtime configuration properties. Exposes things like `container_id` or `application_id` (for when running inside a container).
Also delete unnecessary `SkeinConfigurationProperties` exception (unused since previous release).

Add runtime properties mapping 

---

java/src/main/java/com/anaconda/skein/ApplicationMaster.java
skein/test/test_kv.py

Previously the following steps would result in inconsistent ownership
state in the key-value store:
- Create a key
- Assign an owner to that key
- Delete the key
- Create the key again, without an owner
At this point the key-value store would say the key was unowned, but the
``ServiceTracker`` would still have the key in its set of owned keys.
We now test for this case, and owned keys from their service trackers
upon deletion.

Ensure consistent ownership state

---

java/pom.xml
java/src/main/java/com/anaconda/skein/Daemon.java
java/src/main/java/com/anaconda/skein/Model.java
java/src/main/java/com/anaconda/skein/MsgUtils.java
java/src/main/proto/skein.proto
setup.py
skein/model.py
skein/test/test_core.py
skein/test/test_model.py

Prior to this commit the Daemon only accquired a delegation token for
defaultFs which did not work well in the presence of federation. Now the
application spec contains a list the namenodes to acquire the delegation
token for in addition to defaultFs. In theory, all tokens should be
automatically renewed by the RM. However, I did not have the occasion
to test this.

Added support for ViewFs

---

continuous_integration/travis/docker_install.sh
java/src/main/java/com/anaconda/skein/Daemon.java
skein/test/test_core.py

When an application is killed, remove the application staging directory if it exists.
Fixes #69.

Cleanup appdir for killed applications

---

java/pom.xml
java/src/main/java/com/anaconda/skein/WebUI.java

Accidentally added a jar that was java-8 only (I would have thought
specifying the compiler in maven as 7 would have prevented that, but it
did not). Downgrading jetty version to last java-7 compatible release,
and a tiny api change fixes things.

Fix accidental java-8 only jar

---

docs/source/api.rst
java/src/main/java/com/anaconda/skein/ApplicationMaster.java
java/src/main/java/com/anaconda/skein/Daemon.java
java/src/main/java/com/anaconda/skein/Model.java
java/src/main/java/com/anaconda/skein/MsgUtils.java
java/src/main/java/com/anaconda/skein/Utils.java
java/src/main/java/com/anaconda/skein/WebUI.java
java/src/main/proto/skein.proto
java/src/test/java/com/anaconda/skein/TestUtils.java
skein/__init__.py
skein/model.py
skein/proto/__init__.py
skein/test/test_core.py
skein/test/test_model.py

Adds support for Access Control Lists (ACLs). This allows filtering permissions on users/groups. Three access categories are supported:
- VIEW: view application details. This comes from yarn, we only forward the request.
- MODIFY: modify application.  This comes from yarn, we only forward the request. AFAICT this only disables support for others killing the application.
- UI: access the web ui. This is implemented in skein.
The first two are just forwarding application acls to YARN, and match YARN's semantics and defaults. Note that while these parameters will be forwarded in all cases, YARN will ignore them unless the cluster has been properly configured. See https://www.cloudera.com/documentation/enterprise/6/6.0/topics/cm_mc_yarn_service1.html for more information.
By default, ACLs are …

Support for ACLs

---

docs/source/api.rst
docs/source/debugging.rst
docs/source/specification.rst
java/pom.xml
java/src/main/java/com/anaconda/skein/ApplicationMaster.java
java/src/main/java/com/anaconda/skein/Daemon.java
java/src/main/java/com/anaconda/skein/Model.java
java/src/main/java/com/anaconda/skein/MsgUtils.java
java/src/main/java/com/anaconda/skein/Utils.java
java/src/main/java/com/anaconda/skein/WebUI.java
java/src/main/proto/skein.proto
java/src/main/resources/log4j.properties
skein/__init__.py
skein/core.py
skein/model.py
skein/objects.py
skein/proto/__init__.py
skein/test/conftest.py
skein/test/test_core.py
skein/test/test_model.py

This PR encompasses several changes:
- Adds a `master` top-level field to our configuration. This can be added to later to more deeply customize operation of the application master process, but for now contains only fields influencing logging configuration.
- Adds a `master.log_config` field, allowing for overriding the default `log4j.properties` file. This can be useful when debugging, as you can increase the amount of information from skein or its dependencies.
- Adds a `master.log_level` field, allowing for changing only the log level of skein (not its dependencies).
- Switching our logging to use `slf4j` instead of `log4j`. This has 2 benefits:
- Ability to parametrize messages instead of manually constructing strings. This is both more legible and more performant when those messages …

Logging and debugging improvements

---

docs/source/key-value-store.rst
docs/source/quickstart.rst
docs/source/recipes-ipython-kernel.rst
docs/source/recipes-jupyter-notebook.rst
docs/source/specification.rst
examples/echo_server/spec.yaml
examples/pricing_dashboard/spec.yaml
skein/compatibility.py
skein/model.py
skein/test/test_model.py

Previously we requested memory as an integer in MiB, we now allow (and
prefer) that memory is specified as a string with units.
Note that the default unit is MiB (mebibytes) not MB (megabytes). This
is a carryover from YARN, and is unlikely to change.
Fixes #86.

Add support for human-readable memory specs

---

java/src/main/java/com/anaconda/skein/ApplicationMaster.java
java/src/main/proto/skein.proto
skein/core.py
skein/proto/__init__.py
skein/test/test_core.py

Adds a `set_progress` method to an application, allows updating progress
reports for applications that have a known amount of work to do.
Fixes #88.

Add ability to set progress for running application

---

skein/kv.py

Previously the wrapped kv methods doc signatures would miss the first
parameter (due to a missing `self` in the wrapped method signature). We
now wrap `cls.__init__` instead, fixing the issue.

Fix wrapped kv methods

---

skein/core.py
skein/test/test_core.py

This was accidentally made required in #96. This makes it no longer required, and adds a test to ensure future behavior.

Remove need for JAVA_HOME to be defined

---

docs/source/specification.rst
java/src/main/java/com/anaconda/skein/Daemon.java
java/src/main/java/com/anaconda/skein/Model.java
java/src/main/java/com/anaconda/skein/MsgUtils.java
java/src/main/proto/skein.proto
setup.cfg
skein/cli.py
skein/core.py
skein/model.py
skein/proto/__init__.py
skein/test/test_core.py

Adds support for submitting applications to run as a username different than the submitting user's username. This requires that the submitter have proxy-user permissions to proxy as those accounts.

Add proxy-user support

---

java/src/main/java/com/anaconda/skein/MsgUtils.java
java/src/main/resources/log4j.properties

- MapR filesystem doesn't have a host in the normalized form, was leading to a null-pointer exception. We now check for this and handle it properly.
- ZooKeeper logging is incredibly verbose, turn it down to WARN by default.

A few fixes to add MapR support

---

docs/source/api.rst
docs/source/specification.rst
java/pom.xml
java/src/main/java/com/anaconda/skein/Daemon.java
java/src/main/java/com/anaconda/skein/Model.java
java/src/main/java/com/anaconda/skein/MsgUtils.java
java/src/main/proto/skein.proto
skein/__init__.py
skein/cli.py
skein/core.py
skein/model.py
skein/proto/__init__.py
skein/test/conftest.py
skein/test/test_cli.py
skein/test/test_core.py
skein/test/test_model.py
skein/utils.py

Allows specifying security configuration as part of the application spec. TLS credentials can be specified either as file locations or as raw bytestrings. This allows for launching applications with differing TLS credentials from the same originating daemon.
Also quiets a noisy extraneous log message from grpc >= 1.15 when using fork + exec. This noisy extraneous message should be fixed in a future release of grpc (1.17?), but for now it's better to just quiet it ourselves.
Fixes #102.

 Make security configurable per application 

---

skein/compatibility.py
skein/core.py
skein/kv.py
skein/test/test_kv.py

The abstract base classes in `collections` were moved to
`collections.abc` in Python 3.3, but they were still available to import
from `collections`. Python 3.7 added deprecation warnings when the
instances in `collections` are used, and they will be fully removed from
`collections` in Python 3.8.

Import abstract classes from collections.abc

---

java/pom.xml
java/src/main/resources/kv.mustache.html
java/src/main/resources/services.mustache.html

This applies some filters on what's included in the jar to reduce the overall jar size. We filter out:
- Web resources we don't actually need
- Some java packages that are unnecessary
- Native libraries for non-linux systems (we don't currently work on windows anyway, which isn't a problem for most hadoop installs)
- The whole maven folder, as we're not a package
- All the *.proto files, as these aren't needed at runtime
We also make log4j a provided dependency, which should be true as long as hadoop doesn't change things.
These changes combined remove around 5 MB from the overall jar, bringing us from ~13 MiB to ~8 MiB.
Fixes #106.

Reduce size of jar

---

java/pom.xml
java/src/main/java/com/anaconda/skein/ApplicationMaster.java
java/src/main/proto/skein.proto

This shaves another 1 MiB off the final jar size (down to 7.4 MiB). Since *most* applications won't be sending many many messages, the performance hit here should be minimal.
At this point the bulk of the jar is guava. I tried to use proguard to slim this down, but couldn't (easily) figure out how to accomplish this. For now I'm ok with the current jar size.
Continues to address #106.

Use Protobuf Lite

---

skein/core.py
skein/model.py
skein/test/test_model.py

Previously this wasn't done, leading to errors if the spec wasn't already an ApplicationSpec.
Fixes #110.

Normalize spec before submitting in submit_and_connect

---

docs/source/changelog.rst
java/src/main/java/com/anaconda/skein/Daemon.java
skein/cli.py
skein/core.py
skein/test/test_core.py

Support having the daemon login from a keytab/principal pair. This allows for creation of long running services, as there's no longer a worry about the kerberos ticket expiring.
Fixes #103.

Support login from keytab

---

docs/source/api.rst
docs/source/changelog.rst
docs/source/debugging.rst
docs/source/quickstart.rst
docs/source/recipes-ipython-kernel.rst
docs/source/recipes-jupyter-notebook.rst
docs/source/specification.rst
java/src/main/java/com/anaconda/skein/Driver.java
java/src/main/proto/skein.proto
java/src/main/resources/log4j.properties
skein/__init__.py
skein/cli.py
skein/core.py
skein/exceptions.py
skein/proto/__init__.py
skein/test/test_cli.py
skein/test/test_core.py

Rename "Daemon" to "Driver"
The "Daemon" process name has been confusing for some users, here we rename it to "Driver" to better reflect its purpose and usage. We smoothly deprecate the following names:
- `DaemonError` -> `DriverError`
- `DaemonNotRunningError` -> `DriverNotRunningError`
- `Client.start_global_daemon` -> `Client.start_global_driver`
- `Client.stop_global_daemon` -> `Client.stop_global_driver`
- `skein daemon ...` -> `skein driver ...`
The documentation has also been updated to reflect this change.

Rename daemon to driver

---

java/src/main/java/com/anaconda/skein/ApplicationMaster.java
java/src/main/java/com/anaconda/skein/Driver.java
java/src/main/java/com/anaconda/skein/Utils.java
skein/core.py
skein/model.py
skein/test/test_core.py

Two fixes to make the Skein driver/client work properly inside a YARN container:
- Properly set `io.netty.native.workdir` for the driver as well as the application master
- Load the current application's security configuration by default when run inside a container
This allows applications to be submitted from inside a YARN container just as easily as from the edge node.

Driver works in YARN container

---

docs/source/api.rst
docs/source/quickstart.rst
docs/source/specification.rst
java/src/main/java/com/anaconda/skein/ApplicationMaster.java
java/src/main/java/com/anaconda/skein/Driver.java
java/src/main/java/com/anaconda/skein/Model.java
java/src/main/java/com/anaconda/skein/MsgUtils.java
java/src/main/java/com/anaconda/skein/Utils.java
java/src/main/proto/skein.proto
skein/model.py
skein/test/conftest.py
skein/test/test_core.py
skein/test/test_model.py

Allows running a single user process on the application master. This allows singleton services to start up *much* faster.
The master process also manages the lifetime of the application - when the process exits the application shuts down automatically, regardless of the state of other services. The application final status is determined by the exit code of the process (0 for succeeded, anything else for failed).
This can be useful for running things like the dask client for [dask-yarn submit](http://yarn.dask.org/en/latest/submit.html) (more robustly ensure the cluster shutsdown after submission) or starting single processes like a jupyter notebook server (used in [yarnspawner](https://github.com/jcrist/yarnspawner) to launch jupyterhub on YARN).
Fixes #118.

Optionally run application on master node

---

docs/source/debugging.rst
docs/source/distributing-files.rst
docs/source/key-value-store.rst
docs/source/quickstart.rst
docs/source/recipes-ipython-kernel.rst
docs/source/recipes-jupyter-notebook.rst
docs/source/specification.rst
java/src/main/java/com/anaconda/skein/ApplicationMaster.java
java/src/main/java/com/anaconda/skein/Driver.java
java/src/main/java/com/anaconda/skein/Model.java
java/src/main/java/com/anaconda/skein/MsgUtils.java
java/src/main/java/com/anaconda/skein/Utils.java
java/src/main/proto/skein.proto
skein/model.py
skein/recipes/ipython_kernel.py
skein/recipes/jupyter_notebook.py
skein/test/conftest.py
skein/test/test_cli.py
skein/test/test_core.py
skein/test/test_model.py
skein/test/test_ui.py

Deprecate the ``commands`` field in favor of ``script`` instead.
This removes the oddness of us composing a script from a list of
commands, as well as the automatic addition of ``set -x -e``.
Fixes #121.

Deprecate ``commands`` for ``script``

---

skein/cli.py
skein/core.py
skein/test/conftest.py
skein/test/test_cli.py
skein/test/test_core.py

Previously the global driver would only be stopped if skein could verify
that the corresponding PID was actually a skein driver. In the case of
credential mismatch this could result in an inability to stop a running
driver using the skein cli. This adds a `--force` option to always kill
the process, even if we're not sure if it's a driver.
Addresses comment here: https://github.com/jcrist/skein/issues/124#issuecomment-450892520

Add ``skein driver stop --force``

---

java/src/main/java/com/anaconda/skein/ApplicationMaster.java
java/src/main/java/com/anaconda/skein/Driver.java
skein/test/test_core.py

- Don't propogate CLASSPATH to script running on application master
- Don't attempt to acquire an RM delegation token if one has already been acquired.
This allows launching applications from inside a container, as well as using libhdfs (e.g. pyarrow's hdfs) without extra configuration in the driver script.

A few fixups for running driver in container

---

skein/core.py
skein/test/conftest.py
skein/test/test_cli.py
skein/test/test_core.py
skein/utils.py

Previously we'd fail loudly if the driver file had a pid/address that was no longer correct. Users would have to run:
```
skein driver stop --force
skein driver start
```
in these situations to get a new working global driver. Now we check if the PID doesn't exist, and handle these cases specially:
- `skein driver start` warns that an old driver had died, and starts a new one.
- `skein driver stop` no longer requires `--force` to handle this case (`--force` is still required if the PID exists, but can't be connected with).
Fixes #140

Check if PID exists in global driver

---

docs/source/specification.rst
java/src/main/java/com/anaconda/skein/ApplicationMaster.java
java/src/main/java/com/anaconda/skein/Model.java
java/src/main/java/com/anaconda/skein/MsgUtils.java
java/src/main/proto/skein.proto
skein/model.py
skein/test/test_core.py

Adds support for allowing failures in a service. If set to True, the
application will not terminate if the number of failures for a service
exceeds `max_restarts` for that service. Default is False.
This is useful for things like `dask` workers, where we may want to
handle restart behavior manually instead of relying on skein to do it
for us.

Add `allow_failures` field

---

skein/model.py
skein/test/test_model.py

Keys in the `files` field must be filenames only (no directories
allowed). Previously this was checked only in the server, now we
validate it in the client as well.
Fixes #139.

Validate targets in `files` in the client

---

skein/core.py
skein/model.py
skein/test/test_core.py

Adds `container_dir` attribute to `skein.properties`. If running in a
container, this is the absolute path of the container working directory,
otherwise this is `None`.
Fixes #138.

Expose container working dir in properties

---

skein/model.py
skein/test/test_core.py
skein/test/test_utils.py
skein/utils.py

Previously if multiple processes ran `Security.from_default()` for the first time concurrently, there'd be a race condition generating the new credentials. Now we use a file lock to synchronize between processes.
Fixes #144.

Make generating new credentials threadsafe

---

skein/__init__.py
skein/cli.py
skein/core.py
skein/exceptions.py
skein/model.py
skein/test/test_core.py
skein/test/test_model.py

Removes previously deprecated functionality:
- `DaemonError`
- `DaemonNotRunningError`
- `Client.start_global_daemon`
- `Client.stop_global_daemon`
- `commands` parameter to `Service`
- `skein daemon` CLI commands

Remove deprecated functionality

---

java/src/main/java/com/anaconda/skein/ApplicationMaster.java
java/src/main/proto/skein.proto
skein/core.py
skein/test/test_core.py

Support scaling a service by a delta in number of containers rather than
specifying the number of total containers. This can be useful if
container lifetimes are being managed by some external service rather
than the skein appmaster itself.

Support scaling by a delta instead of total count

---

skein/core.py
skein/test/test_core.py

Fixes a bug (introduced in 0.6.0) in detecting the absolute path to the
container directory.  YARN (at least some versions) will create all
possible container directories (as listed in
`yarn.nodemanager.local-dirs`, but only populate one of them. Previously
we were just looking for a directory to exist when searching for the
container directory, now we look for the proper files as well.

Fix skein.properties.container_dir

---

docs/source/api.rst
java/src/main/java/com/anaconda/skein/Driver.java
java/src/main/java/com/anaconda/skein/MsgUtils.java
java/src/main/proto/skein.proto
skein/__init__.py
skein/core.py
skein/model.py
skein/proto/__init__.py
skein/test/test_core.py
skein/test/test_model.py

Adds a method `skein.Client.get_nodes` for accessing information about nodes in the YARN cluster. Information exposed includes node hostnames, available resources, etc...
Fixes #155.

Expose node information through client

---

docs/source/api.rst
java/src/main/java/com/anaconda/skein/Driver.java
java/src/main/java/com/anaconda/skein/MsgUtils.java
java/src/main/proto/skein.proto
skein/core.py
skein/model.py
skein/proto/__init__.py
skein/test/test_core.py
skein/test/test_model.py

Adds methods to `skein.Client` for querying the status of yarn queues.

Add API for querying queue states

---

java/src/main/java/com/anaconda/skein/Driver.java
java/src/main/proto/skein.proto
skein/cli.py
skein/core.py
skein/proto/__init__.py
skein/test/test_cli.py
skein/test/test_core.py

Adds support for moving an application between queues. This is doable
using either the python API (`skein.Client.move_application`) or the CLI
('skein application mv`).

Add method to move application to another queue

---

java/src/main/java/com/anaconda/skein/Driver.java
java/src/main/java/com/anaconda/skein/MsgUtils.java
java/src/main/proto/skein.proto
skein/cli.py
skein/core.py
skein/test/test_core.py
skein/test/test_model.py
skein/test/test_utils.py
skein/utils.py

Allows filtering applications on:
- state
- name
- user
- queue
- start and finish times
These filters are also exposed through the CLI.
Fixes #133.

Add filter methods to `Client.get_applications`

---

java/pom.xml
java/src/main/java/com/anaconda/skein/ApplicationMaster.java
java/src/main/java/com/anaconda/skein/Driver.java
java/src/main/java/com/anaconda/skein/Utils.java
setup.py

Adds the skein version (as determined by versioneer) to the jar, and
logs the version in both the driver and application master processes.
This is useful for debugging from logs, as it gives the exact commit
that was run to produce those logs.

Add skein version to jar

---

.travis.yml
continuous_integration/travis/before_install.sh
continuous_integration/travis/script.sh
docs/source/develop.rst
skein/test/conftest.py
skein/test/test_cli.py
skein/test/test_core.py
skein/test/test_ui.py

This adds a branch to our build matrix for testing with Hadoop 3 (a CDH6 cluster). All but one test passed as is, so things already worked fine with Hadoop 3 before this PR.
The failing test was checking that submitting an application as a user you don't have permissions to proxy as fails with an error. For some reason in Hadoop 3 this operation no longer errors, but instead logs error messages and hangs forever in a retry loop. I spent some time trying to find a hack around this to prevent this from happening and gave up. Since this is just testing that we have good error message for a rare situation that is already incorrect, I'm ok skipping this test on Hadoop 3 for now.
Fixes #153.

Enable testing for Hadoop 3

---

java/src/main/java/com/anaconda/skein/Driver.java
skein/core.py
skein/test/conftest.py
skein/test/test_cli.py
skein/test/test_model.py

This makes 2 major changes:
- Uses 127.0.0.1 explicitly instead of localhost for the driver address.
This (hopefully) removes issues of Java resolving to ipv6 and python
resolving to ipv4.
- Changes the driver to only listen locally, instead of on 0.0.0.0. Note
that this wasn't a security issue before (all communication was still
secured), but having the driver reachable from a different machine isn't
a use case we should support.
Fixes #165

Bind driver to 127.0.0.1 instead of localhost

---

skein/core.py
skein/test/test_core.py

Unpickling will only work on the same machine the driver is running on.
This is mostly useful for starting a single temporary client and using
it in child processes via multiprocessing.
See https://github.com/jcrist/skein/issues/140#issuecomment-486669563

Make `skein.Client` picklable

---

skein/utils.py

This mistakenly used `AttributeError` instead of `ImportError`.

Fix grpc version check code

---

docs/source/specification.rst
java/src/main/java/com/anaconda/skein/Driver.java
java/src/main/java/com/anaconda/skein/MsgUtils.java
java/src/main/java/com/anaconda/skein/Utils.java
java/src/main/proto/skein.proto
skein/model.py
skein/objects.py
skein/test/test_core.py
skein/test/test_model.py

Adds (limited) support for Hadoop 3 resource requests. Currently only
the builtin resource extensions (gpu and fpga) are supported, true
custom requests could be added later with greater effort.
If the version of hadoop or the configuration don't support these
resources, a nice error is thrown.
Fixes #154.

Support GPU and FPGA resources

---

java/src/main/java/com/anaconda/skein/ApplicationMaster.java
skein/test/test_core.py

A skein application is intended to shutdown given any of the following conditions:
- A user defined script running on the application master exits
- A container exits with a non-zero exit code, and its corresponding service is out of retries
- All containers have finished and no script is running on the application master
Unfortunately the logic implementing the second one was broken, and a test was never added (the other 2 are already tested). This adds requisite tests and fixes the bug.
Fixes #172.

Fix shutdown condition

---

skein/core.py
skein/test/test_core.py

GRPC doesn't cleanup channels on stub deletion automatically, leading to
resource leaks in applications that create and destroy many clients. We
now close channels explicitly for both `skein.Client` and
`skein.ApplicationClient`.

Cleanup channel resources for clients

---

continuous_integration/travis/docker_install.sh
continuous_integration/travis/script.sh
docs/source/api.rst
skein/test/conftest.py
skein/test/test_tornado.py
skein/tornado.py

Adds mixins for `kerberos` and `simple` authentication, for writing tornado-backed services that launch YARN jobs, or interact with YARN in any way.
I've written a few services lately like this, and have just been copying around the same short authenticator classes, figured it might make sense to push these upstream. This adds no dependencies, the addition of these mixin classes is purely for ease of use when writing YARN-backed services.

Tornado Auth mixins

---

java/src/main/java/com/anaconda/skein/ApplicationMaster.java

fixes #220 
This fix re-includes GPUs in the resource list which is being used for consistency checking, and therefore allows execution of skein on yarn clusters with GPU support.

Fix GPU resource check

---

setup.py

`grpcio` 1.45.0 is "yanked" on PyPI and cause a source based installation fail because `setup.py` doesn't realize how to avoid installing a yanked version even though `pip` would.

Fix setup.py failure caused by PyPI yanked package: grpcio=1.45.0
