jcrist/skein

- java/src/main/java/com/anaconda/skein/Daemon.java
- java/src/main/proto/skein.proto
- skein/cli.py
- skein/compatibility.py
- skein/core.py
- skein/exceptions.py
- skein/model.py
Adds callback handling for queue'd applications, so the client can block until the application has started. Also cleans up and improves error handling.
> Add ability to wait on queue'd applications

- .coveragerc
- skein/cli.py
- skein/core.py
- skein/test/conftest.py
- skein/test/test_cli.py
- skein/test/test_core.py
Add tests for CLI functionality. Also a few fixes to docstrings, and a few code simplifications.
> Add CLI tests

- docs/source/index.rst
- docs/source/quickstart.rst
- docs/source/recipes-ipython-kernel.rst
- docs/source/recipes.rst
- skein/recipes/ipython_kernel.py
- skein/recipes/jupyter_notebook.py
- Cleanup ipython-kernel and jupyter-notebook recipes
- Add recipes documentation section
- Document ipython-kernel recipe
> Cleanup and document recipes

- docs/source/develop.rst
- docs/source/index.rst
- docs/source/recipes-ipython-kernel.rst
- docs/source/recipes-jupyter-notebook.rst
> Add Developer docs

- .travis.yml
- continuous_integration/travis/before_install.sh
- continuous_integration/travis/build_docs.sh
- continuous_integration/travis/docker_install.sh
- continuous_integration/travis/install.sh
- continuous_integration/travis/script.sh
- docs/source/develop.rst
- setup.py
Allow for building only docs, speeding up travis builds when the full test suite isn't needed.
> Use conditional builds on travis

- docs/source/_static/custom.css
- docs/source/distributing-files.rst
- docs/source/index.rst
- docs/source/specification.rst
Add a docs page describing how file distribution works.
> Document file distribution

- docs/source/debugging.rst
- docs/source/index.rst
A few quick notes on how to access the logs.
> Add docs on debugging

- docs/source/distributing-files.rst
Add docs on how to distribute virtual environments.
Partially addresses #62.
> Add docs on using venv-pack with Skein

- continuous_integration/travis/script.sh
- docs/source/distributing-files.rst
- Fix travis ci flake8 to flake8 code directory. Previously this was
accidentally running on the whole repository.
- Small edit to docs.
> A few small fixups

- docs/source/_static/favicon.ico
- docs/source/_static/logo.svg
- docs/source/conf.py
- Add favicon.ico
- Add logo to doc page
> Add logo to docs

- .gitignore
- skein/test/test_core.py
There's a few periodic failures on travis, trying to debug them here.
> [WIP] debug travis failures

- docs/source/index.rst
- docs/source/quickstart.rst
- examples/echo_server/README.rst
- examples/pricing_dashboard/README.rst
- Add a highlights section
- Add a readme to the echo_server example
- "commandline"/"command line" -> "command-line"
> A few cleanups to the docs [skip-tests]

- docs/source/changelog.rst
- java/src/main/java/com/anaconda/skein/ApplicationMaster.java
- java/src/main/proto/skein.proto
- skein/cli.py
- skein/core.py
- skein/test/test_core.py
Allows users to specify more diagnostics information for failed applications on shutdown.
> Support custom diagnostic messages on shutdown

- java/src/main/java/com/anaconda/skein/Daemon.java
- skein/test/conftest.py
- skein/test/test_core.py
Previously the daemon server would hang if the user hadn't kinit'd
before running an operation. This is due to `UserGroupInformation` not
caring if no credentials were found on init and only checking when an
operation is attempted, coupled with the errors being logged only (no
way to catch failed login at call time, the yarnclient just hangs).
We now manually check if credentials are missing before doing any
operation that might hang, and error accordingly. Once
`UserGroupInformation` has been init'd, there's no way to reset (it will
never look for a kerberos ticket again), the daemon has to be restarted.
This is annoying.
To make sure the user clients always get a nice error message (instead
of a failed connection) we hang around and respond only with errors
saying to "kinit and restart …
> Error nicely if not logged in

- docs/source/debugging.rst
- docs/source/distributing-files.rst
- java/src/main/java/com/anaconda/skein/ApplicationMaster.java
- java/src/main/java/com/anaconda/skein/Daemon.java
- java/src/main/resources/log4j.properties
- skein/cli.py
- skein/core.py
- skein/test/test_core.py
- Makes the log level in the skein daemon configurable
- Improves the logging messages generated by the daemon
- Adds a docs section on how to configure logging in the daemon
> Improve logging in daemon

- skein/test/test_core.py
This was previously untested, but can be easily tested with the `monkeypatch` fixture in pytest.
> Add a test for `ApplicationClient.from_current`

- java/pom.xml
Configuration wasn't *quite* correct. Fixup for #111.
> Fix shading of javax packages

- skein/cli.py
- skein/core.py
- skein/test/test_core.py
- will be used to tune -XX:ParallelGCThreads for example (by default creates one thread for each available core on the driver)
> Be able to inject additional java options into skein driver

- java/src/main/java/com/anaconda/skein/ApplicationMaster.java
Some YARN configurations return ``Resource`` instances on allocation
that have vcores always set to 1 (even though the allocated container
has access to the requested number of vcores). This led to skein not
matching the allocated resource to any containers when the requested
vcores > 1. Now we ignore vcores on matching, and use only the requested
vcores throughout.
Fixes https://github.com/dask/dask-yarn/issues/48
> Don't match on vcores for allocated containers

- java/src/main/java/com/anaconda/skein/Driver.java
- skein/test/test_core.py
Application staging directories are currently cleaned up on application
completion, regardless of failure. However, if failure occurs during
submission they may not be cleaned up. This PR ensures that cleanup
occurs, even during submission failure. A test is included to verify
this.
> Cleanup appdir on submit failure

- setup.py
> Better error in setup.py if maven is missing

- skein/utils.py
Hello,
Here is the PR following the discussion here: https://github.com/jcrist/skein/issues/167
> Fork support for skein Clients when grpcio>=1.18.0

- java/pom.xml
I've never developed in Java, but I went on a debugging spree to understand what went wrong that made me need to investigate a lot of things. This PR includes some notes on what a lot of plugins does etc in the `pom.xml` file that would have saved me some time as a java novice when trying to pinpoint my issue.
> Add inline comments to pom.xml to help the java novice debug

- docs/source/changelog.rst
This is a changelog entry for a 0.8.2 release.
Note that I've also accompanied instructions on how to build this project and cut a release in:
- #245
> Update changelog for release [skip-tests]
